config/routes.rb
Rails.application.routes.draw do
  get 'sessions_hospital/new'

  get 'static_pages/home'

  get 'static_pages/help'
  
  get 'hospitals/index'

  resources :atendimentos
  resources :hospitals
  resources :pacientes
  
  root 'static_pages#home'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get    '/loginhospital',   to: 'sessions_hospital#new'
  post   '/loginhospital',   to: 'sessions_hospital#create'
  delete '/logouthospital',  to: 'sessions_hospital#destroy'
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  has_many :atendimentos, dependent: :destroy
  validates :nome,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: {message:"não pode estar vazio."}, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_nil: true
  validates :cep,  presence: true, length: { is: 8}
  
  def feed
    Atendimento.where("paciente_id = ?", id)
  end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :logged_in_paciente, only: [:edit, :update, :destroy]
  before_action :correct_paciente,   only: [:edit, :update, :destroy]
  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
    @paciente = Paciente.find(params[:id])
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
    @paciente = Paciente.find(params[:id])
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        log_in @paciente
        format.html { redirect_to @paciente, notice: 'Paciente foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @paciente }
        else
          format.html { render :new }
          format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    @paciente = Paciente.find(params[:id])
    if @paciente.update_attributes(paciente_params)
      flash[:success] = "Perfil Atualizado"
      redirect_to @paciente
    else
      render 'edit'
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Paciente excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:nome, :endereco, :data_nasc, :rg, :cpf, :email, :password, :telefone, :password_confirmation, :cep, :rua, :numero, :cidade, :bairro, :estado)
    end
    
    
    def correct_paciente
      @paciente = Paciente.find(params[:id])
      redirect_to(root_url) unless current_paciente?(@paciente)
    end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<%= form_with(model: paciente, local: true) do |form| %>
  <% if paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paciente.errors.count, "erro") %> impediram usuário de ser salvo:</h2>

      <ul>
      <% paciente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class= "col-md-4">
  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :paciente_nome %>
  </div>
  
  <div class="field">
    <%= form.label :data_nascimento %>
    <%= form.date_select :data_nasc, {order: [:day, :month, :year]}, id: :paciente_data_nasc %>
  </div>
  
  <div class="field">
    <%= form.label :RG %>
    <%= form.text_field :rg, id: :paciente_rg %>
  </div>
  
  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, id: :paciente_cpf %>
  </div>
  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :paciente_telefone, placeholder:"(00)(0)0000-0000" %>
  </div>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :paciente_email, placeholder:"example@example.com"%>
  </div>
  <div class="field">
    <%= form.label :senha %>
    <%= form.password_field :password, id: :paciente_password %>
  </div>
  <div class="field">
    <%= form.label :confirmação_de_senha %>
    <%= form.password_field :password_confirmation, id: :paciente_passwordconfirmation %>
  </div>
  
</div>
<div class="col-md-4">
  <div class="field">
      <%= form.label :CEP %>
      <%= form.text_field :cep, id: :cep, onblur: "pesquisacep(this.value)", placeholder:"00000000" %>
  </div>
  <div class="field">
    <%= form.label :endereço %>
    <%= form.text_field :endereco, id: :paciente_endereco %>
  </div>

  <div class="field">
      <%= form.label :bairro %>
      <%= form.text_field :bairro, id: :paciente_bairro %>
  </div>
   
  
</div>
<div class="col-md-4">
  <div class="field">
    <%= form.label :numero %>
    <%= form.text_field :numero, id: :paciente_numero %>
  </div>
  <div class="field">
      <%= form.label :cidade %>
      <%= form.text_field :cidade, id: :paciente_cidade %>
  </div>
  <div class="field">
      <%= form.label :estado %>
      <%= form.text_field :estado, id: :paciente_estado %>
  </div>
  
  <div class="actions cadastro_paciente center">
    <input type="submit" value="Confirmar" class= "btn btn-info center"> </input>
  </div>
</div>
<% end %>

app/views/pacientes/edit.html.erb
<h1 class="title">Editar informações pessoais</h1>
<%= render 'form', paciente: @paciente %>
<div="container">
<button class="btn btn-danger center destroy">
  <%= link_to 'Excluir Cadastro', @paciente, method: :delete, data: { confirm: 'Você tem certeza?' } %>
</button>
</div>

app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pacientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Data nasc</th>
      <th>Rg</th>
      <th>Cpf</th>
      <th>Email</th>
      <th>Senha</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.nome %></td>
        <td><%= paciente.endereco %></td>
        <td><%= paciente.data_nasc %></td>
        <td><%= paciente.rg %></td>
        <td><%= paciente.cpf %></td>
        <td><%= paciente.email %></td>
        <td><%= paciente.senha %></td>
        <td><%= paciente.telefone %></td>
        <td><%= link_to 'Show', paciente %></td>
        <td><%= link_to 'Edit', edit_paciente_path(paciente) %></td>
        <td><%= link_to 'Destroy', paciente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paciente', new_paciente_path %>

app/views/pacientes/new.html.erb
<h1 class='title'>Cadastro Paciente</h1>

<%= render 'form', paciente: @paciente %>

<%= link_to 'Back', pacientes_path %>

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Oi, <%= @paciente.nome %>, </strong>
  <p>Esse é o resumo do seu perfil: </p>
  
</p>
<div class="col-md-8">
  <p>Email: <%= @paciente.email %></p>
  <p>Endereço: <%= @paciente.endereco %>,<%= @paciente.numero %> - <%= @paciente.bairro %> | <%= @paciente.cidade %> - <%= @paciente.estado %> </p>
</div>

<div class="col-md-4">
    <p>Você possui:</p> 
    <ul>
    <li> Atendimentos
    <% if @paciente.atendimentos.any? %>
      (<%= @paciente.atendimentos.count %>)
    <% end %>
    </li>
    <li> Receituários </li>
    <li> Prontuários </li>
    </ul>
  </div>