config/routes.rb
Rails.application.routes.draw do
  get 'sessions_hospital/new'

  get 'static_pages/home'

  get 'static_pages/help'
  
  get 'hospitals/index'

  resources :atendimentos
  resources :hospitals
  resources :pacientes
  
  root 'static_pages#home'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get    '/loginhospital',   to: 'sessions_hospital#new'
  post   '/loginhospital',   to: 'sessions_hospital#create'
  delete '/logouthospital',  to: 'sessions_hospital#destroy'
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :atendimentos, dependent: :destroy
  validates_presence_of :nome, :numero, :cep, :cnpj, :telefone
  validates :nome, length: { maximum: 50}
  validates :endereco, length: { maximum: 50}
  validates :numero, length: { maximum: 10}
  validates :cep, length: { is: 8 }
  validates :cidade, length: { maximum: 50}
  validates :estado, length: { maximum: 50}
  validates :bairro, length: { maximum: 50}
  validates :cnpj, length: { maximum: 50}
  validates :telefone, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255},
                    format: { with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }
  validates :senha, length: { minimum: 6,maximum: 20, message:"tem que ter entre 6 e 20 caracteres" }, allow_nil: true
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :set_hospital, only: [:show, :edit, :update, :destroy]
  # GET /hospitals
  # GET /hospitals.json
  def index
    @hospitals = Hospital.all
  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
  end

  # GET /hospitals/new
  def new
    @hospital = Hospital.new
  end

  # GET /hospitals/1/edit
  def edit
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(hospital_params)
    
    respond_to do |format|
      if @hospital.save
        loghospital_in @hospital
        format.html { redirect_to @hospital, notice: 'Hospital foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @hospital }
        else
            format.html { render :new }
            format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hospitals/1
  # PATCH/PUT /hospitals/1.json
  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html { redirect_to @hospital, notice: 'Hospital was successfully updated.' }
        format.json { render :show, status: :ok, location: @hospital }
      else
        format.html { render :edit }
        format.json { render json: @hospital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital.destroy
    respond_to do |format|
      format.html { redirect_to hospitals_url, notice: 'Hospital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_params
      params.require(:hospital).permit(:nome, :endereco, :numero, :cep, :cidade, :estado, :bairro, :cnpj, :telefone, :email, :senha)
    end
    
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.erb
<%= form_with(model: hospital, local: true) do |form| %>
  <% if hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% hospital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-4">
  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :hospital_nome %>
  </div>
  <div class="field">
    <%= form.label :cnpj %>
    <%= form.text_field :cnpj, id: :hospital_cnpj %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :hospital_telefone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :hospital_email %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.password_field :senha, id: :hospital_senha %>
  </div>
  </div>
  <div class="col-md-4">
    <div class="field">
      <%= form.label :cep %>
      <%= form.text_field :cep, id: :cep, onblur: "pesquisacephospital(this.value)", placeholder:"00000000"  %>
    </div>
    <div class="field">
      <%= form.label :endereco %>
      <%= form.text_field :endereco, id: :hospital_endereco %>
    </div>
    <div class="field">
      <%= form.label :cidade %>
      <%= form.text_field :cidade, id: :hospital_cidade %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="field">
      <%= form.label :numero %>
      <%= form.text_field :numero, id: :hospital_numero %>
    </div>
    <div class="field">
      <%= form.label :bairro %>
      <%= form.text_field :bairro, id: :hospital_bairro %>
    </div>
    <div class="field">
      <%= form.label :estado %>
      <%= form.text_field :estado, id: :hospital_estado %>
    </div>
    <div class="actions cadastro_paciente center">
    <input type="submit" value="Cadastrar" class= "btn btn-info center"> </input>
    </div>
  </div>
  
<% end %>

app/views/hospitals/edit.html.erb
<h1 class="title">Editar Informações do Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Show', @hospital %> 
<div class="container">
<button class="btn btn-danger center destroy">
  <%= link_to 'Excluir Cadastro', @hospital, method: :delete, data: { confirm: 'Você tem certeza?' } %>
</button>
</div>

app/views/hospitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hospitais</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereço</th>
      <th>CNPJ</th>
      <th>Telefone</th>
      <th>Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @hospitals.each do |hospital| %>
      <tr>
        <td><%= hospital.nome %></td>
        <td><%= hospital.endereco %>, <%= hospital.numero %> - <%= hospital.bairro %> | <%= hospital.cidade %> - <%= hospital.estado %></td>
        <td><%= hospital.cnpj %></td>
        <td><%= hospital.telefone %></td>
        <td><%= hospital.email %></td>
        <td><%= link_to 'Show', hospital %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/hospitals/new.html.erb
<h1 class="title">Cadastrar Hospital</h1>

<%= render 'form', hospital: @hospital %>

<%= link_to 'Back', hospitals_path %>

app/views/hospitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @hospital.nome %>
  <p id="notice"><%= notice %></p>
<div class="col-md-8">
  <p>Email: <%= @hospital.email %></p>
  <p>Endereço: <%= @hospital.endereco %>,<%= @hospital.numero %> - <%= @hospital.bairro %> | <%= @hospital.cidade %> - <%= @hospital.estado %> </p>
</div>

</p>