config/routes.rb
Rails.application.routes.draw do
  get 'sessions_hospital/new'

  get 'static_pages/home'

  get 'static_pages/help'
  
  get 'hospitals/index'

  resources :atendimentos
  resources :hospitals
  resources :pacientes
  
  root 'static_pages#home'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get    '/loginhospital',   to: 'sessions_hospital#new'
  post   '/loginhospital',   to: 'sessions_hospital#create'
  delete '/logouthospital',  to: 'sessions_hospital#destroy'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    código disponível em <a href="https://github.com/anacls/sistema-ps">Github</a>
    <p>feito por: Ana Carolina, Fábio Vieira, Pedro Moraes</p>
  </small>
  <a href='static_pages/help'>Política de Privacidade</a>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  
    <nav>
      <div class="container"><%= link_to image_tag("logo.png", alt: "logo"), root_path %>
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "Início", root_path %></li>
        
        <% if logged_in? %>
          <li><%= link_to "Pacientes", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               Minha Conta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Conta", current_paciente %></li>
              <li><%= link_to "Configurações", edit_paciente_path(current_paciente) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <% if loggedhospital_in? %>
            <li><%= link_to "Hospitals", '#' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Minha Conta <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Conta", current_hospital %></li>
                <li><%= link_to "Configurações", edit_hospital_path(current_hospital) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logouthospital_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Login Paciente", login_path %></li>
            <li><%= link_to "Login Hospital", loginhospital_path %></li>
          <% end %>
        <% end %>
      </ul>
    </nav>
  </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SUStentacao</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

 <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>